javac GrafischerTaschenrechnerMitPlotter.java
jar cvfe GrafischerTaschenrechnerMitPlotter.jar GrafischerTaschenrechnerMitPlotter GrafischerTaschenrechnerMitPlotter.class
java GrafischerTaschenrechnerMitPlotter